# -*- coding: utf-8 -*-
"""SRK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15S_Du7Grmvi_P2l-RS64TtwhuuyJkly8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Load dataset
df = pd.read_csv('SRK_12.csv')
df = df.replace({'Yes': 1, 'No': 0})  # Convert Yes/No to 1/0
df.drop(columns=['Movie Title'], inplace=True)

# Define X and y
X = df.drop(columns=['Bollywood Blockbuster'])
y = df['Bollywood Blockbuster']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train SVM model
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

# Print metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"Specificity: {specificity:.4f}")

# Print top 4 most important features based on coefficients
coef = model.coef_[0]
top_features = pd.Series(coef, index=X.columns).abs().sort_values(ascending=False).head(4)
print("\nTop 4 Important Features:")
print(top_features)



